FROM ubuntu:22.04

# Install required packages
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    cmake \
    g++ \
    git \
    wget \
    libpthread-stubs0-dev \
    python3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

# Build the application
RUN mkdir -p build && \
    cd build && \
    cmake .. && \
    make

EXPOSE 8000

CMD ["./build/movieApp", "8000"]